version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.2
      - image: circleci/postgres:9.4
      - image: circleci/node:6.10

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
